FROM openjdk:8

ARG MIRTH_DOWNLOAD_URL='http://downloads.mirthcorp.com/connect/3.6.1.b220/mirthconnect-3.6.1.b220-unix.tar.gz'

COPY mysql-apt-config_0.8.15-1_all.deb /tmp/

RUN apt-get clean && apt-get update && apt-get install -y --no-install-recommends locales postgresql-client lsb-release \
    && echo 4 | dpkg -i /tmp/mysql-apt-config_0.8.15-1_all.deb \
    && apt-get update && apt-get install -y mysql-community-client \
    && sed -i 's/^# *\(en_US.UTF-8\)/\1/' /etc/locale.gen && locale-gen
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8

RUN curl -SL ${MIRTH_DOWNLOAD_URL} \
    | tar -xzC /opt \
    && mv "/opt/Mirth Connect" /opt/connect

RUN useradd -u 1000 mirth
RUN mkdir -p /opt/connect/appdata && chown -R mirth:mirth /opt/connect/appdata

VOLUME /opt/connect/appdata
VOLUME /opt/connect/custom-extensions
WORKDIR /opt/connect
RUN rm -rf cli-lib manager-lib \
    && rm mirth-cli-launcher.jar mirth-manager-launcher.jar mccommand mcmanager
RUN (cat mcserver.vmoptions; echo "") > mcserver_base.vmoptions
EXPOSE 8443 21000 21001 21002

COPY entrypoint.sh /
RUN chmod 755 /entrypoint.sh
ENTRYPOINT [ "/entrypoint.sh" ]

RUN chown -R mirth:mirth /opt/connect
USER mirth
CMD ["./mcserver"]
